#!/usr/bin/env bash
# This script automates the process of changing the Gnome Display Manager(gdm)
# login background image.
# Autor: Thiago Silva
# Contact: thiagos.dasilva@gmail.com
# URL: https://github.com/thiggy01/gdm-change-login-background
# ========================================================================== #

# Add the restore option in order to restore gdm original theme.
if [ "$1" = "--restore" ]; then
  cat /usr/share/gnome-shell/theme/gdm3.css~ > /usr/share/gnome-shell/theme/\
gdm3.css
  echo "Login background sucessfully restored to its original theme."
  echo "Restart Gnome to apply change."
  exit 0
fi

# Get the image selected by user from yad based GUI.
usrInput=`yad --file --center --width=900 --height=450 --title "Select An \
Image File" --add-preview --file-filter "Image Files | *.jpg *.png" 2> /dev/null`

# Verify if yad is installed
if [ $? == 127 ]; then
     echo "yad package is not installed."
     echo "It is needed for GUI."
     echo "Exiting."
     exit 1
fi

# Check if there is a user input.
[ -z "$usrInput" ] && exit 1

# Test if argument is an image file.
if [[ $(file --mime-type -b "$usrInput") == image/*g ]]; then

    # Get the full path of submited image.
    imgPath=$(realpath "$usrInput")
    imgName=$(basename "$usrInput")

    # Save pictures to /usr/share/gdm-backgrounds.
    [ ! -d /usr/share/gdm/saved-pictures ] && mkdir /usr/share/gdm/saved-pictures
    cp "$imgPath" /usr/share/gdm/saved-pictures
    bgImgPath=/usr/share/gdm/saved-pictures/"$imgName"

    # Ubuntu GDM login background configuration file path.
    cssPath=/usr/share/gnome-shell/theme/gdm3.css
    
    # Test if there is a backup of the original gdm css file and create a backup,
    # if there isn't one. 
    [ ! -f "$cssPath"~ ] && cp "$cssPath" "$cssPath"~ 

    # Change the login background image to the one you submited.
    ex $cssPath << EOF
/#lockDialogGroup
:normal jf:ld}a url(file://$bgImgPath);obackground-size: cover; }
:wq
EOF

    # Test if login screen background was changed.
    if grep -wq "$bgImgPath" "$cssPath"; then
	yad --title "Sucessful Message" --center \
	    --width=300 --height=100 --borders=20 \
	    --text="Login image sucessfully changed." \
	    --button=gtk-ok
	yad --title "Restart Question" --center \
	    --width=300 --height=100 --borders=20 \
	    --text="Restart Gnome to apply change?" \
	    --button=gtk-yes:1 --button=gtk-no:2
	ret=$?
	if [ $ret == 1 ]; then
	    killall -3 gnome-shell
	elif [ $ret == 2 ]; then
	    yad --title "Warning Message" --center \
		--width=300 --height=100 --borders=20 \
		--text="Change won't be applied until restart." \
		--button=gtk-ok
	fi
    fi
fi
