#!/bin/bash

# This script automates the process of changing the Gnome Display
# Manager(gdm) login background image.

# Test if argument is an image file.
if [[ $(file --mime-type -b "$1") = image/*g ]] 

then
# Get the full path of submited image.
	imgPath=$( realpath "$1" )
# Ubuntu GDM login background configuration file path.
	cssPath=/usr/share/gnome-shell/theme/gdm3.css
# Change the login background image to the one you submited.
	ex $cssPath << EOF
/#lockDialogGroup
:normal jf(lvf)hdifile://$imgPath
:%s/background-repeat: repeat/background-size: cover/
:wq
EOF
# Test if login screen background was changed.
	grep -q $imgPath $cssPath
	if [ $? == 0 ]
	then
		echo "Login background image sucessfully changed."
		echo "Restart gdm or reboot to apply this change." 
	fi

# If no image file was submited, ask for proper submission.
else
	echo "Please, submit an .jpg, .jpeg or .png image file."
	echo "Usage: sudo ./ubuntu-change-login-background path/to/image.*g" 

fi
